generator_architecture: FCN
generator_model_type: regression

generator:
  weight_decay: 0.
  optimizer: adam
  learning_rate: 0.0004
  beta1: 0.5
  beta2: 0.999

  params:
    input_size: 67
    hidden_channel: 32 
    out_channel: 5