generator_architecture: NODE
generator_model_type: classification

generator:
  weight_decay: 0.
  optimizer: adam
  learning_rate: 0.001
  beta1: 0.5
  beta2: 0.999

  params:
    input_size: 67
    layer_dim: 64
    num_layers: 4
    tree_dim: 5
    depth: 6
