generator_architecture: NODE
generator_model_type: regression

generator:
  weight_decay: 0.
  optimizer: adam
  learning_rate: 0.0004
  beta1: 0.5
  beta2: 0.999

  params:
    input_size: 67
    layer_dim: 64 
    num_layers: 8
    tree_dim: 3
    depth: 6
