generator_architecture: NODE
generator_model_type: classification

generator:
  weight_decay: 0.
  optimizer: qhadam

params:
  input_size: 67
  layer_dim: 64
  num_layers: 3
  tree_dim: 5
  depth: 6
