batch_size: 2048
num_workers: 10
max_epoch: 1000
starting_epoch: 0
display_step: 100
critic_step: 10
device: cuda

features_names:
  - RichDLLe
  - RichDLLk
  - RichDLLmu
  - RichDLLp
  - RichDLLbt

checkpoint_path:
save_path: /home/dikrivenkov/rich/experiments/
gan_type: js
seed: 42
experiment_data: 25.04.2021

neptune:
  project_name: danji/rich
  experiment_name: rich
  tags:
    - rich
    - jsgan
