batch_size: 2048
num_workers: 10
max_epoch: 1000
starting_epoch: 117
display_step: 500
critic_step: 4
repetitions: 300
noise_dim: 32
device: cuda:0


features_names:
  - RichDLLe
  - RichDLLk
  - RichDLLmu
  - RichDLLp
  - RichDLLbt

checkpoint_path: /home/dikrivenkov/rich/experiments/js_NODE_NODE_28.04.2021/epoch_117_iter_0.pt
save_path: /home/dikrivenkov/rich/experiments/
gan_type: js
seed: 42
experiment_data: 28.04.2021

neptune:
  project_name: danji/rich
  experiment_name: rich
  tags:
    - rich
    - jsgan
