batch_size: 1024
num_workers: 2
max_epoch: 1000
starting_epoch: 0
display_step: 100
critic_step: 10
repetitions: 300
c_lambda: 10
noise_dim: 64
device: cuda

features_names:
  - RichDLLe
  - RichDLLk
  - RichDLLmu
  - RichDLLp
  - RichDLLbt

checkpoint_path:
save_path: /content/drive/MyDrive/rich/
gan_type: wgan

neptune:
  project_name: danji/rich
  experiment_name: rich
  tags:
    - rich
    - jsgan