batch_size: 1024
num_workers: 10
max_epoch: 1000
starting_epoch: 0
display_step: 800
critic_step: 10
repetitions: 300
freeze_generator: false
c_lambda: 10
noise_dim: 64
device: cuda

features_names:
  - RichDLLe
  - RichDLLk
  - RichDLLmu
  - RichDLLp
  - RichDLLbt

checkpoint_path:
save_path: /content/drive/MyDrive/rich/
gan_type: wgan
seed: 42
experiment_data: 16.05.2021

neptune:
  project_name: danji/rich
  experiment_name: rich
  tags:
    - rich
    - wgan
