critic_architecture: NODE
critic_model_type: regression

critic:
  weight_decay: 0.
  optimizer: adam
  learning_rate: 0.001
  beta1: 0.5
  beta2: 0.999

  params:
    input_size: 8
    layer_dim: 64 
    num_layers: 2
    tree_dim: 1
    depth: 6
