critic_architecture: NODE
critic_model_type: classification

critic:
  weight_decay: 0.
  optimizer: qhadam

  params:
    input_size: 8
    layer_dim: 64
    num_layers: 4
    tree_dim: 1
    depth: 6
