critic_architecture: NODE
critic_model_type: classification

critic:
  weight_decay: 0.
  optimizer: adam
  learning_rate: 0.0004
  beta1: 0.5
  beta2: 0.999

  params:
    input_size: 8
    layer_dim: 128 
    num_layers: 4
    tree_dim: 3
    depth: 6